### ISSUE TITLE
Any further development planned?

### ISSUE THREAD

**Issue by Rainer-Lang** [h6ah4i/android-tablayouthelper#2]
I don't know if it's possible, but I have some ideas. ;-)
How about to add badges to tablayout or make the tablayout/viewpager not swipeable,...

**Comment by h6ah4i** [comment]
Hi. Thanks for your suggestions. 

> add badges to tablayout

That is easy. Just implement custom tab views. 

However, I think it should not be included to this library. Because I want this library keep small and simple. 
I have already made a custom tab example, is that not enough for you?

> make the tablayout/viewpager not swipeable,...

Maybe that is impossible unless overriding the onInterceptTouchEvent() method of  ViewPager class.

**Comment by Rainer-Lang** [comment]
I have a tablayout and a recyclerview with swipe. The swipe of the viewpager collidates with the swipe of the recyclerview.

**Comment by h6ah4i** [comment]
Sorry for the VERY VERY late reply 😞 

> I have a tablayout and a recyclerview with swipe. The swipe of the viewpager collidates with the swipe of the recyclerview.

That feature won't be added in this library. This library is just a helper of `TabLayout` class, not `ViewPager`.

---

I have been added a example app which uses `ViewPager` and swipeable feature of Advanced RecyclerView library. The key idea is creating a custom `ViewGroup` which is placed at the root of each pages ([`PagerSwipeItemFrameLayout`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.2/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s_viewpager/PagerSwipeItemFrameLayout.java)).

This custom class overrides `canScrollHorizontally` method and it returns `true` when `ViewPager` should not handle touch events.

https://github.com/h6ah4i/android-advancedrecyclerview/tree/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s_viewpager
