### ISSUE TITLE
Compatibility issue with support library 28.0.0-beta01

### ISSUE THREAD

**Issue by mpfeiffermway** [h6ah4i/android-tablayouthelper#9]
After updating our application from Android support library from version 27.1.1 to version 28.0.0-beta01 the application now fails to start (to test compatibility on a Pixel 2 with Android P and target SDK 28)

We see the following error on startup:
```
E/UncaughtException: java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/<app-name>/base.apk)
        at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:327)
        at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.<init>(TabLayoutHelper.java:98)
```

The crash happens here:
```
protected TabLayout.OnTabSelectedListener mInternalOnTabSelectedListener;

tabLayout.addOnTabSelectedListener(mInternalOnTabSelectedListener);
```

So it seems this library is no longer compatible with support library version 28

**Comment by h6ah4i** [comment]
Hi, thank you for your report. I confirmed that v0.9.0 is compatible with the official release of support library v28.0.0.

**Comment by troy379** [comment]
Hey @h6ah4i !
I'm also facing the same issue using of 28.0.0 version of `support libraries` and 0.9.0 of `tablayouthelper`. Any thoughts about this?

**Comment by h6ah4i** [comment]
@troy379 Hi. Could you try v0.9.1 instead? It's built with support library v28.0.0.

**Comment by troy379** [comment]
Oh, I've migrated the project to AndroidX and now using the `1.0.0` version. Thanks for your response anyway, maybe it'll be useful for someone who still wants to use support libraries 🙂
Cheers!
